### ISSUE TITLE
ZeroDivisionError in eval

### ISSUE THREAD

**Issue by kilian-gebhardt** [andreasvc/disco-dop#49]
If the gold data does not contain function tags but the system output does, then a ZeroDivisionError is raised. 

The problem occurs for instance, while running:

```
discodop eval no-functions.txt functions.txt

Traceback (most recent call last):
  File "/home/user/.local/bin/discodop", line 11, in <module>
    load_entry_point('disco-dop==0.6a0', 'console_scripts', 'discodop')()
  File "/home/user/.local/lib/python3.6/site-packages/disco_dop-0.6a0-py3.6-linux-x86_64.egg/discodop/cli.py", line 45, in main
    fromlist=['main']), 'main')()
  File "/home/user/.local/lib/python3.6/site-packages/disco_dop-0.6a0-py3.6-linux-x86_64.egg/discodop/eval.py", line 656, in main
    evaluator.breakdowns()
  File "/home/user/.local/lib/python3.6/site-packages/disco_dop-0.6a0-py3.6-linux-x86_64.egg/discodop/eval.py", line 81, in breakdowns
    self.funcbreakdown(limit)
  File "/home/user/.local/lib/python3.6/site-packages/disco_dop-0.6a0-py3.6-linux-x86_64.egg/discodop/eval.py", line 190, in funcbreakdown
    100 * sum(acc.goldbfunc[cat].values()) / len(acc.goldfun),
ZeroDivisionError: division by zero
```

[functions.txt](https://github.com/andreasvc/disco-dop/files/1382893/functions.txt)
[no-functions.txt](https://github.com/andreasvc/disco-dop/files/1382894/no-functions.txt)

**Comment by andreasvc** [comment]
Thanks!

I never encountered this bug because I only consider the original unmodified treebank files a proper "gold standard", which always contain function tags.
