### ISSUE TITLE
Cython error installing disco-dop

### ISSUE THREAD

**Issue by SebasJoustra** [andreasvc/disco-dop#58]
I am receiving this error when trying to install disco-dop. This happens both on Ubuntu and MacOS. This may be an issue on my side, but I can't figure it out. I am on python 3.6.5, Cython 0.28.2 and Numpy 1.14.2

```
MacBook-Pro-van-Sebastiaan:disco-dop sebastiaan$ env CC=gcc sudo python3 setup.py install
Compiling discodop/_fragments.pyx because it changed.
Compiling discodop/bit.pyx because it changed.
Compiling discodop/coarsetofine.pyx because it changed.
Compiling discodop/containers.pyx because it changed.
Compiling discodop/disambiguation.pyx because it changed.
Compiling discodop/estimates.pyx because it changed.
Compiling discodop/kbest.pyx because it changed.
Compiling discodop/pcfg.pyx because it changed.
Compiling discodop/plcfrs.pyx because it changed.
[1/9] Cythonizing discodop/_fragments.pyx
warning: discodop/_fragments.pyx:1033:31: Unused entry 'genexpr'
[2/9] Cythonizing discodop/bit.pyx
[3/9] Cythonizing discodop/coarsetofine.pyx
warning: discodop/coarsetofine.pyx:104:32: Unused entry 'genexpr'
[4/9] Cythonizing discodop/containers.pyx
warning: discodop/_grammar.pxi:124:23: Unused entry 'genexpr'
warning: discodop/_grammar.pxi:212:16: local variable 'data' might be referenced before assignment
warning: discodop/_grammar.pxi:309:35: local variable 'data' might be referenced before assignment
warning: discodop/containers.pyx:572:16: local variable 'buf' might be referenced before assignment
warning: discodop/containers.pyx:578:44: local variable 'buf' might be referenced before assignment

Error compiling Cython file:
------------------------------------------------------------
"""Lookup production ID. Return -1 when not seen before."""
    cdef Rule rule
    cdef char *tmp = <char *>&rule
    res = self.labels.get(r[0], None)
    if res is None:
      return None
         ^
------------------------------------------------------------

discodop/containers.pyx:955:10: Cannot assign None to int
Traceback (most recent call last):
  File "setup.py", line 121, in <module>
    language_level=3,
  File "/usr/local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1026, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1146, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: discodop/containers.pyx

**Comment by andreasvc** [comment]
Thanks for the report. I fixed this particular error, but it seems that there are more errors with the new Cython version that I'll have to sort out.
